name: Setup @aws-amplify/cli
description: Installs the @aws-amplify/cli npm package

author: "philip-gai"
branding:
  icon: "upload-cloud"
  color: "orange"

inputs:
  cache_dependencies:
    description: "Whether to cache the installed @aws-amplify/cli or not. Uses actions/cache."
    required: false
    default: "false"
  cli_version:
    description: "The version of @aws-amplify/cli to install."
    required: false
    default: "latest"
  node_version:
    description: "The version of node to setup. See https://github.com/actions/setup-node."
    required: false
  registry_url:
    description: 'Optional registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file, and set up auth to read in from env.NODE_AUTH_TOKEN'
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup node ${{ inputs.node_version }}
      uses: actions/setup-node@v2
      with:
        node-version: "${{ inputs.node_version }}"
        registry-url: "${{ inputs.registry_url }}"
    - if: inputs.cache_dependencies == 'true'
      name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: aws-amplify-cli-cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-amplify-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-amplify-${{ env.cache-name }}-
          ${{ runner.os }}-amplify-
          ${{ runner.os }}-
    - name: Install @aws-amplify/cli@${{ inputs.cli_version }}
      shell: bash
      run: |
        npm install -g @aws-amplify/cli@${{ inputs.cli_version }}
